자신이 관심있는 증권 종목 미래 가격 예측하기

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
url = 'http://finance.naver.com/item/sise_day.nhn?code=005930&page='
x_list = []
max_num = 15
for i in range(1,max_num):
    a = pd.read_html(url+str(i), index_col=0)
    x_list.append(a[0].dropna().values.astype(np.int))
x_list


[array([[   46250,      350,    46200,    46900,    45850,  8434869],
        [   46600,      400,    47350,    47400,    46250, 11383522],
        [   47000,      500,    47000,    47000,    46700, 12949231],
        [   46500,      800,    46000,    46600,    45750, 12603534],
        [   45700,      100,    45800,    46000,    45600,  9226097],
        [   45600,      100,    45200,    45800,    45200,  7076774],
        [   45500,      200,    45200,    45800,    45200,  6085066],
        [   45700,      200,    45750,    45800,    45200,  9454913],
        [   45500,      150,    44850,    45500,    44850,  7147785],
        [   45350,     1000,    45450,    45450,    45000, 10417690]]),
 array([[   44350,      450,    43750,    44500,    43650,  7994928],
        [   43900,      100,    43750,    44050,    43400, 11890424],
        [   44000,      250,    43750,    44150,    43300,  9322873],
        [   43750,      850,    44200,    44400,    43400, 16906541],
        [   44600,

In [66]:
xx_list = np.reshape(x_list,[-1,6])
X=xx_list[:,0]

In [67]:
window_week=4
window_day=window_week * 5 # 5일
predict_day = 5
window_day

20

In [73]:
offset=30
before = X[:-predict_day] # 최근 데이터 5개 빼고
later = X[window_day:] # 과거 데이터 20개 빼고
before.shape, later.shape

((2315,), (2300,))

In [74]:
m = len(X) - (predict_day + window_day -1)
m

2296

In [75]:
x_list = []
y_list = []
for i in range(m):
    x = X[i:i+window_day] # 1 to 21 ... 20일간의 데이터
    y = X[i+window_day:i+window_day+predict_day] # 그다음 5일간의 데이터
    x_list.append(x) # 날짜 인덱스 빼고 값만 저장
    y_list.append(y)

In [77]:
X = np.array(x_list)
y = np.array(y_list)

In [78]:
X_train = X[offset:]
X_test = X[:offset]
y_train = y[offset:]
y_test = y[:offset]
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2266, 20), (30, 20), (2266, 5), (30, 5))

In [79]:
from sklearn.linear_model import LinearRegression, Ridge
lr = Ridge().fit(X_train, y_train)

In [80]:
lr.predict(X_test)

array([[46324.82484422, 46666.07405408, 46716.80667706, 46089.8174655 ,
        45563.56264514],
       [46737.04894312, 46822.63758335, 46083.70609831, 45554.99521303,
        45577.63544776],
       [46823.28840363, 46084.66817505, 45554.96797975, 45577.99648754,
        45605.54634305],
       [46083.80262673, 45554.43868229, 45576.58149674, 45604.38463648,
        45542.32938973],
       [45553.82506162, 45575.7992646 , 45604.1815884 , 45541.52541261,
        45426.25890096],
       [45576.19202225, 45604.29125793, 45542.43949264, 45426.60031341,
        44917.13048665],
       [45604.39122804, 45542.62771973, 45426.51957035, 44916.90923217,
        44136.16946704],
       [45544.01766302, 45427.74725268, 44918.40051372, 44137.14335143,
        43950.75124213],
       [45427.83416151, 44918.66116133, 44136.85415836, 43950.69567195,
        43867.26667262],
       [44918.12823536, 44136.86226026, 43949.18677853, 43866.41060197,
        44117.63373147],
       [44135.91282928, 43947.

In [81]:
lr.score(X_train, y_train), lr.score(X_test, y_test)

(0.9525011479505396, 0.8919508526340407)

In [86]:
# 미래의 환률그래프 시각화
최근20일데이터 = X[-window_day:]
미래의5일예측 = lr.predict(최근20일데이터)

In [90]:
X

array([[46250, 46600, 47000, ..., 44200, 43900, 43450],
       [46600, 47000, 46500, ..., 43900, 43450, 46600],
       [47000, 46500, 45700, ..., 43450, 46600, 47000],
       ...,
       [38650, 38650, 39100, ..., 38350, 38800, 38650],
       [38650, 39100, 38900, ..., 38800, 38650, 38650],
       [39100, 38900, 39150, ..., 38650, 38650, 39100]])