In [1]:
#요소들끼리 더하고 싶다 : element wise add
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [2]:
(1,2,3)+(7,4,5)

(1, 2, 3, 7, 4, 5)

Lit, Dict, Set 연산용으로 사용이 불가능, 메모리 사용량이 크고 느립니다.

In [7]:
import numpy as np

In [8]:
#배열 만들기
# 함수 사용시 shift + tab으로 설명을 봅니다.
numpy.arange(1,10), numpy.arange(1,10,2)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [9]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

야후 파이낸스의 SP500 주식 데이터를 읽습니다.
csv 혹은 pandas로 읽을 수 있습니다.

In [10]:
import pandas

In [11]:
stock = pandas.read_csv('^GSPC.csv')
stock.shape

(20, 7)

In [12]:
stock

Date         Open         High          Low        Close  \
0   2019-05-20  2841.939941  2853.860107  2831.290039  2840.229980   
1   2019-05-21  2854.020020  2868.879883  2854.020020  2864.360107   
2   2019-05-22  2856.060059  2865.469971  2851.110107  2856.270020   
3   2019-05-23  2836.699951  2836.699951  2805.489990  2822.239990   
4   2019-05-24  2832.409912  2841.360107  2820.189941  2826.060059   
5   2019-05-28  2830.030029  2840.510010  2801.580078  2802.389893   
6   2019-05-29  2790.250000  2792.030029  2766.060059  2783.020020   
7   2019-05-30  2786.939941  2799.000000  2776.739990  2788.860107   
8   2019-05-31  2766.149902  2768.979980  2750.520020  2752.060059   
9   2019-06-03  2751.530029  2763.070068  2728.810059  2744.449951   
10  2019-06-04  2762.639893  2804.489990  2762.639893  2803.270020   
11  2019-06-05  2818.090088  2827.280029  2800.919922  2826.149902   
12  2019-06-06  2828.510010  2852.100098  2822.449951  2843.489990   
13  2019-06-07  2852.870117  2884.969971  2852.870117  2873.340088   
14  2019-06-10  2885.830078  2904.770020  2885.510010  2886.729980   
15  2019-06-11  2903.270020  2910.610107  2878.530029  2885.719971   
16  2019-06-12  2882.729980  2888.570068  2874.679932  2879.840088   
17  2019-06-13  2886.239990  2895.239990  2881.989990  2891.639893   
18  2019-06-14  2886.820068  2894.449951  2879.620117  2886.979980   
19  2019-06-17  2889.750000  2897.270020  2887.300049  2889.669922   

      Adj Close      Volume  
0   2840.229980  3288870000  
1   2864.360107  3218700000  
2   2856.270020  3192510000  
3   2822.239990  3891980000  
4   2826.060059  2887390000  
5   2802.389893  4121410000  
6   2783.020020  3700050000  
7   2788.860107  3273790000  
8   2752.060059  3981020000  
9   2744.449951  3943810000  
10  2803.270020  3810430000  
11  2826.149902  3548830000  
12  2843.489990  3396410000  
13  2873.340088  3220250000  
14  2886.729980  3209210000  
15  2885.719971  3548420000  
16  2879.840088  3034130000  
17  2891.639893  3069810000  
18  2886.979980  2922330000  
19  2889.669922  1579314342

In [15]:
arr = np.array(stock) # 배열로 전환
arr.shape

(20, 7)

In [21]:
arr[0], arr[0,:]#첫번째 행


(array(['2019-05-20', 2841.939941, 2853.860107, 2831.290039, 2840.22998,
        2840.22998, 3288870000], dtype=object),
 array(['2019-05-20', 2841.939941, 2853.860107, 2831.290039, 2840.22998,
        2840.22998, 3288870000], dtype=object))

In [19]:
arr[0,0], arr[-1,-1] # 첫번째행의첫번째열, 마지막행의 마지막열

('2019-05-20', 1579314342)

In [22]:
# open만 가져오자
o = arr[:,1]
o

array([2841.939941, 2854.02002, 2856.060059, 2836.699951, 2832.409912,
       2830.030029, 2790.25, 2786.939941, 2766.149902, 2751.530029,
       2762.639893, 2818.090088, 2828.51001, 2852.8701170000004,
       2885.830078, 2903.27002, 2882.72998, 2886.23999, 2886.820068,
       2889.75], dtype=object)

In [35]:
# b(below) 이래쪽에 셀 만들기
# open의 최대값, 최소값, 평균을 구해보자
# 내장 함수(import 없이 바로 사용 가능한 함수)
max(o), min(o), np.max(o), np.min(o), np.mean(o), np.median(o), np.std(o)

(2903.27002,
 2751.530029,
 2903.27002,
 2751.530029,
 2837.1390014000003,
 2839.319946,
 45.016996538592394)

In [25]:
# close를 가져오자
close = arr[:,4] # 도 가능하지만
print(close)
close = arr[:, -3] # 이 편합니다.
print(close)

[2840.22998 2864.360107 2856.27002 2822.23999 2826.060059 2802.389893
 2783.02002 2788.860107 2752.060059 2744.449951 2803.27002 2826.149902
 2843.48999 2873.340088 2886.72998 2885.719971 2879.840088 2891.639893
 2886.97998 2889.669922]
[2840.22998 2864.360107 2856.27002 2822.23999 2826.060059 2802.389893
 2783.02002 2788.860107 2752.060059 2744.449951 2803.27002 2826.149902
 2843.48999 2873.340088 2886.72998 2885.719971 2879.840088 2891.639893
 2886.97998 2889.669922]


In [38]:
# open high low close 4개의 컬럼만 뽑자
# 시작:끝
otoc = arr[:,1:-2] # 1:5
otoc

array([[2841.939941, 2853.860107, 2831.290039, 2840.22998],
       [2854.02002, 2868.8798829999996, 2854.02002, 2864.360107],
       [2856.060059, 2865.469971, 2851.110107, 2856.27002],
       [2836.699951, 2836.699951, 2805.48999, 2822.23999],
       [2832.409912, 2841.360107, 2820.189941, 2826.060059],
       [2830.030029, 2840.51001, 2801.580078, 2802.389893],
       [2790.25, 2792.030029, 2766.060059, 2783.02002],
       [2786.939941, 2799.0, 2776.73999, 2788.860107],
       [2766.149902, 2768.97998, 2750.52002, 2752.060059],
       [2751.530029, 2763.070068, 2728.810059, 2744.449951],
       [2762.639893, 2804.48999, 2762.639893, 2803.27002],
       [2818.090088, 2827.280029, 2800.919922, 2826.149902],
       [2828.51001, 2852.100098, 2822.449951, 2843.48999],
       [2852.8701170000004, 2884.969971, 2852.8701170000004, 2873.340088],
       [2885.830078, 2904.77002, 2885.51001, 2886.72998],
       [2903.27002, 2910.610107, 2878.530029, 2885.719971],
       [2882.72998, 2888.570068

In [39]:
otoc.shape

(20, 4)

In [42]:
np.max(otoc, axis=0), np.max(otoc, axis=1)

(array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object),
 array([2853.860107, 2868.8798829999996, 2865.469971, 2836.699951,
        2841.360107, 2840.51001, 2792.030029, 2799.0, 2768.97998,
        2763.070068, 2804.48999, 2827.280029, 2852.100098, 2884.969971,
        2904.77002, 2910.610107, 2888.570068, 2895.23999, 2894.449951,
        2897.27002], dtype=object))

In [43]:
np.max(arr[:,1:5],axis=0)

array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object)

In [46]:
# argmax, argmin 맥스값의 위치
o, np.max(o), np.argmax(o)

(array([2841.939941, 2854.02002, 2856.060059, 2836.699951, 2832.409912,
        2830.030029, 2790.25, 2786.939941, 2766.149902, 2751.530029,
        2762.639893, 2818.090088, 2828.51001, 2852.8701170000004,
        2885.830078, 2903.27002, 2882.72998, 2886.23999, 2886.820068,
        2889.75], dtype=object), 2903.27002, 15)

In [47]:
np.max(otoc, axis=0), np.argmax(otoc,axis=0)

(array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object),
 array([15, 15, 19, 17], dtype=int64))

In [61]:
arr[:,5]-arr[:,1], np.max(arr[:,5]-arr[:,1]), np.argmax(arr[:,5]-arr[:,1])

(array([-1.7099610000000212, 10.34008700000004, 0.20996100000002116,
        -14.459961000000021, -6.3498530000001665, -27.640135999999984,
        -7.229980000000069, 1.920165999999881, -14.0898430000002,
        -7.080077999999958, 40.6301269999999, 8.059814000000188,
        14.979980000000069, 20.469970999999532, 0.899902000000111,
        -17.550048999999944, -2.8898920000001453, 5.399902999999995,
        0.15991200000007666, -0.08007799999995768], dtype=object),
 40.6301269999999,
 10)

In [65]:
print(arr[np.argmax(arr[:,5]-arr[:,1]),0], " 이 가장 큰 날입니다.")

2019-06-04  이 가장 큰 날입니다.


##### 데이터분석
- 가격 상승하는 날 거래량이 많아질까?
- 전날 가격이 상승하면 다음날 시장가격은 더 높은 가격에서 시작할까?
- 가격 변동이 크면 거래량도 많아질까?

###### 다음 단계 : 예측
- 어제/오늘  현황 분석이 끝났는데 내일은 Open/Close 어떻게 될까
- 방법 : 1. 통계적(R) 2. 머신러닝

가격이 상승한 횟수, 가격이 하락한 횟수

In [76]:
gap = arr[:,5]-arr[:,1]
vol=arr[:,-1]
gap, vol


(array([-1.7099610000000212, 10.34008700000004, 0.20996100000002116,
        -14.459961000000021, -6.3498530000001665, -27.640135999999984,
        -7.229980000000069, 1.920165999999881, -14.0898430000002,
        -7.080077999999958, 40.6301269999999, 8.059814000000188,
        14.979980000000069, 20.469970999999532, 0.899902000000111,
        -17.550048999999944, -2.8898920000001453, 5.399902999999995,
        0.15991200000007666, -0.08007799999995768], dtype=object),
 array([3288870000, 3218700000, 3192510000, 3891980000, 2887390000,
        4121410000, 3700050000, 3273790000, 3981020000, 3943810000,
        3810430000, 3548830000, 3396410000, 3220250000, 3209210000,
        3548420000, 3034130000, 3069810000, 2922330000, 1579314342],
       dtype=object))

In [69]:
# 가격 상승하는 날 거래량이 많아질까?
# 상승한 날의 거래량/ 하락한 날의 거래량
gapu=[]
gapd=[]
for i in gap:
    if i>0:
        gapu.append(i)
    else: 
        gapd.append(i)
gapu, gapd


([10.34008700000004,
  0.20996100000002116,
  1.920165999999881,
  40.6301269999999,
  8.059814000000188,
  14.979980000000069,
  20.469970999999532,
  0.899902000000111,
  5.399902999999995,
  0.15991200000007666],
 [-1.7099610000000212,
  -14.459961000000021,
  -6.3498530000001665,
  -27.640135999999984,
  -7.229980000000069,
  -14.0898430000002,
  -7.080077999999958,
  -17.550048999999944,
  -2.8898920000001453,
  -0.08007799999995768])

In [71]:
# 조건부 검색
a=np.array([1,2,3,4])
even = a%2==0 # 짝수값만 뽑고 싶다
even # 불린 마스크

array([False,  True, False,  True])

In [72]:
a[even] # true 인것만 출력

array([2, 4])

In [79]:
# 상승한 날의 거래량의 평균
print(np.mean(vol[gap>0]), np.mean(vol[gap<0]))

3286227000.0 3397639434.2


In [78]:
# 상승한 날이 거래량이 더 많냐?
np.mean(vol[gap>0]) > np.mean(vol[gap<0])

False

In [82]:
a = np.array([1,2,3])

In [83]:
a, a.dtype, a.shape

(array([1, 2, 3]), dtype('int32'), (3,))

In [84]:
np.zeros((3))


array([0., 0., 0.])

In [86]:
np.zeros(shape=(2,3,4), dtype=np.int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [90]:
np.ones(shape=(3,4,1), dtype=np.int32)

array([[[1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1]]])

In [100]:
np.full((3,4,1),3.14)

array([[[3.14],
        [3.14],
        [3.14],
        [3.14]],

       [[3.14],
        [3.14],
        [3.14],
        [3.14]],

       [[3.14],
        [3.14],
        [3.14],
        [3.14]]])

In [103]:
#사용 빈도 순위 zeros, ones, arange
np.arange(0,10,3)

array([0, 3, 6, 9])

In [105]:
np.linspace(1,10, 5) # 시작값, 끝값, x등분

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [106]:
# width 100M, 건물 3채
np.linspace(0,100,3+1)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [107]:
np.linspace(150, 200, 5)

array([150. , 162.5, 175. , 187.5, 200. ])

In [108]:
import random
random.randint(1,10)

8

In [113]:
np.random.rand(2,3) # 0,1

array([[0.92705849, 0.51628388, 0.68616476],
       [0.11281156, 0.66710379, 0.40629298]])

In [115]:
np.random.normal(size=(2,3))

array([[-0.02684039,  0.86336266,  0.33977941],
       [ 0.15921504, -0.12346244,  0.13470536]])

In [116]:
np.random.randint(low=1, high=10, size=(2,3))

array([[8, 1, 4],
       [6, 8, 5]])

In [117]:
np.random.uniform(size=(2,3)) # 전체값에서 균등하게 뽑힙니다. 제어가능

array([[0.54079802, 0.40078633, 0.71740238],
       [0.95592928, 0.27933842, 0.18857206]])

In [118]:
a = np.ones(shape=(3,2))
b = np.ones(shape=(3,2))
a + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [120]:
a = np.ones(shape=(3,2))
b = np.ones(shape=(3,1)) # broadcasting 숫자가 1일때
a + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [122]:
a = np.ones(shape=(3,2), dtype=np.int)
b = np.ones(shape=(3,2), dtype=np.float)
a + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [123]:
#행우선으로 저장됩니다.
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [138]:
b = a.reshape(2,3)

'''
# Fortran, R 은 열단위 우선 
array([[0, 3],
       [1, 4], 
       [2, 5]])
'''
b



array([[0, 1, 2],
       [3, 4, 5]])

In [133]:
# 차원 갯수, 모양, 총 요소 갯수, 데이터 타입, 메모리 사용량
b.ndim, b.shape, b.size, b.dtype, b.nbytes

(2, (2, 3), 6, dtype('int32'), 24)

In [134]:
b.flatten() # 1차원으로 변환 flatten:평명화

array([0, 1, 2, 3, 4, 5])

In [140]:
# slicing : 데이터 자르기
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- [1,4,7]
- [6,7,8]
- [1,2,4,5,7,8]
- [4,5,7,8]

In [146]:
a[:,1]

array([1, 4, 7])

In [147]:
a[2]

array([6, 7, 8])

In [158]:
a[:,1:3].flatten()

array([1, 2, 4, 5, 7, 8])

In [159]:
a[1:3,1:3].flatten()

array([4, 5, 7, 8])

In [161]:
a[:,1], a[-1], a[:,1:], a[1:,1:]

(array([1, 4, 7]), array([6, 7, 8]), array([[1, 2],
        [4, 5],
        [7, 8]]), array([[4, 5],
        [7, 8]]))

In [166]:
b=np.arange(12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b에서 아래 요소/원소(element)를 잘라(slice)주세요
- [5,6,9,10]
- [9,10,11]

In [173]:
b[1:,1:-1]

array([[ 5,  6],
       [ 9, 10]])

In [171]:
b[-1,1:]

array([ 9, 10, 11])

In [203]:
#3차원
c=np.arange(2*3*4).reshape((2,3,4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [204]:
c[0,0], c[1,0], c[0,:,1], c[1,:,-1]

(array([0, 1, 2, 3]),
 array([12, 13, 14, 15]),
 array([1, 5, 9]),
 array([15, 19, 23]))

In [205]:
#[6,10], [17,18,19],[13,14,17,18]
c[0,1:,2], c[1,1,1:], c[1,:2,1:-1]

(array([ 6, 10]), array([17, 18, 19]), array([[13, 14],
        [17, 18]]))

In [214]:

c.reshape((6,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [221]:
np.reshape(c,(6,4)) # 편한대로 사용

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [222]:
c.reshape(-1,4) # 알아서 맞춤 -1(unknown dimension) 1번만 사용

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [223]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a, b

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [232]:
# 두 배열을 붙입니다. concatenate == concat
np.concatenate((a,b,a,b),axis=0), np.concatenate((a,b,a,b),axis=0).shape, a.shape
# axis=0 -> shape는 앞쪽이 늘어남, 뒷쪽은 고정, 행이 늘어남 

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), (8, 3), (2, 3))

In [230]:
np.concatenate((a,b,a,b),axis=1), np.concatenate((a,b,a,b),axis=1).shape

(array([[ 0,  1,  2,  6,  7,  8,  0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11,  3,  4,  5,  9, 10, 11]]), (2, 12))

data0 = data1.csv
data1 = data2.csv
np.concatenate(data0, data1, axis=0)

In [234]:
# stack 쌓다
a.shape, b.shape

((2, 3), (2, 3))

In [240]:
np.stack((a,b,a),axis=0), np.stack((a,b,a),axis=0).shape
# concat이랑 다르게 차원이 늘어난다. axis로 지정한 곳의 차원(ex. 0)이 늘어남

(array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[ 0,  1,  2],
         [ 3,  4,  5]]]), (3, 2, 3))

In [244]:
np.stack((a,b),axis=1), np.stack((a,b),axis=1).shape

(array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[ 3,  4,  5],
         [ 9, 10, 11]]]), (2, 2, 3))

In [245]:
np.stack((a,b),axis=2), np.stack((a,b),axis=2).shape

(array([[[ 0,  6],
         [ 1,  7],
         [ 2,  8]],
 
        [[ 3,  9],
         [ 4, 10],
         [ 5, 11]]]), (2, 3, 2))

In [247]:
#stack 활용 예
#[첫번째 학생, 두번째학생, 세번째 학생]
kor=[80,90,99]
eng=[70,50,60]
score = np.stack((kor,eng), axis=1)
score
# 학생별 성적

array([[80, 70],
       [90, 50],
       [99, 60]])

In [256]:
math=np.array([20,30,40]).reshape((3,1))
math


array([[20],
       [30],
       [40]])

In [263]:
score2 = np.concatenate((score,math),axis=1) # axis=-1 -> -1은 마지막 차원을 가리킵니다.
score2

array([[80, 70, 20],
       [90, 50, 30],
       [99, 60, 40]])

In [265]:
# 4번째 학생의 국영수 점수가 추가됐습니다.
# 모든 데이터를 하나로 통합하세요.
score_4=np.array([100,90,90]).reshape((1,3))

In [267]:
score3 = np.concatenate((score2,score_4),axis=0)
score3

array([[ 80,  70,  20],
       [ 90,  50,  30],
       [ 99,  60,  40],
       [100,  90,  90]])

In [282]:
# 각 과목별 평균
# 시험을 가장 잘 본 학생의 평균 점수는?
np.mean(score3, axis=0) # 열별 평균

array([92.25, 67.5 , 45.  ])

In [303]:
print(np.argmax(np.mean(score3, axis=1))+1,"번째 학생이", np.max(np.mean(score3, axis=1)),"점으로 평균점수가 가장 높습니다.") 
# 행별 평균



4 번째 학생이 93.33333333333333 점으로 평균점수가 가장 높습니다.


In [306]:
#np.save() #binary file in NumPy ''.npy
# (%10.5f) '%.2f': 소수점 2번째 자리까지 %d 정수만
np.savetxt('score_sample.txt',score3, '%d') #text file

In [310]:
s = np.loadtxt('score_sample.txt')
s, s.shape

(array([[ 80.,  70.,  20.],
        [ 90.,  50.,  30.],
        [ 99.,  60.,  40.],
        [100.,  90.,  90.]]), (4, 3))

In [317]:
s[:,::-1] # 시작부터 끝까지 거꾸로

array([[ 20.,  70.,  80.],
       [ 30.,  50.,  90.],
       [ 40.,  60.,  99.],
       [ 90.,  90., 100.]])

In [319]:
s[:,::2] # 시작부터 끝까지 스텝(간격) 2

array([[ 80.,  20.],
       [ 90.,  30.],
       [ 99.,  40.],
       [100.,  90.]])

In [325]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [327]:
# 시작부터 끝까지 2칸씩 뛰면서
#1번째 요소부터 끝까지 2칸씩 뛰면서
a[::2], a[1::2]

(array([0, 2, 4, 6, 8]), array([1, 3, 5, 7, 9]))

In [329]:
# 2번째 요소부터 6번째 요소까지 2칸씩 뛰면서
# [시작:끝:간격]
a[2:6:2]

array([2, 4])

In [338]:
a[-2::-2], a[::-2]

(array([8, 6, 4, 2, 0]), array([9, 7, 5, 3, 1]))

In [340]:
#분리하기
np.split(a, [3,6]) # 해당위치를 잘라라


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

In [345]:
#분리하기 section 갯수
#머신러닝에서 데이터 셋을 k개 분리해서 k-fold validation set을 만듭니다.
# k=3이라면, 데이터를 3개로 분리해서 2개 셋은 학습, 1개 셋은 테스트로 사용
'''
3-fold validation set
ABC
학습 : AB 테스트 : C
학습 : BC 테스트 : A
학습 : AC 테스트 : B
'''
np.split(a,5) # 5개로 잘라라

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

##### 브로드 캐스팅
배열의 모양이 서로 다를 때 연산이 가능하게 해주는 기능

In [347]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [348]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [351]:
a + np.array([1,2,3,4]).reshape(4,1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [353]:
a=np.array([0,10,20,30])
a=np.stack((a,a,a),1)
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [355]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [356]:
a+b # broadcasting

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [373]:
#c=np.array([0,10,20,30]).reshape(4,1)
c=np.arange(4)*10
c=c.reshape([-1,1])
#d=np.array([0,1,2])
d=np.arange(3)
print(c+d)


[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [374]:
7 == 3

False

In [375]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [377]:
a > 5

array([False, False, False, False, False, False,  True,  True])

In [379]:
b=np.arange(1,9)
a<b

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [384]:
mask = a > 3
print(mask)

[False False False False  True  True  True  True]


In [381]:
# true인 값만 선택됩니다. boolean mask 를 이용한 indexing
a[mask]

array([3, 4, 5, 6, 7])

In [385]:
np.logical_not(mask)

array([ True,  True,  True,  True, False, False, False, False])

In [387]:
np.logical_and(mask, mask)

array([False, False, False, False,  True,  True,  True,  True])

In [388]:
# 짝수이면서 2보다 큰 값을 뽑으세요. logical_and, [mask]를 이용해서
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [389]:
mask0 = a % 2 ==0
mask1 = a > 2
mask0, mask1

(array([ True, False,  True, False,  True, False,  True, False]),
 array([False, False, False,  True,  True,  True,  True,  True]))

In [390]:
np.logical_and(mask0,mask1
              )

array([False, False, False, False,  True, False,  True, False])

In [392]:
a[np.logical_and(mask0,mask1)]

array([4, 6])

In [394]:
#정렬
np.sort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

주식 데이터 2개를 받아서 concatenate로 붙이세요
df = pandas.read_csv()로 파일 읽고
arr0 = np.array(df[]) 필요한 숫자부분만
arr = np.concatenate(arr0, arr1), axis=0)

In [421]:
import pandas
df0=pandas.read_csv('2018.csv')
arr0=np.array(df0)
df1=pandas.read_csv('2019.csv')
arr1=np.array(df1)

In [422]:
#arr0=arr0[:,1:]
#arr1=arr1[:,1:]

In [423]:
arr=np.concatenate((arr0,arr1),axis=0)


In [424]:
arr0.shape, arr1.shape, arr.shape


((251, 7), (251, 7), (502, 7))

# 평균, 최저값, 최대값
- 각 컬럼의 평균값을 구합니다.
- 가격 변동(gap)이 가장 클때, 그게 언제인지?(날짜)

In [442]:
arr_avg=np.mean(arr[:,1:],axis=0).astype(np.int)

In [443]:
arr_avg

array([    24525,     24642,     24399,     24527,     24527, 332232888])

In [436]:
Close = arr[:,4]
Open = arr[:,1]
Gap = np.ab
s(Close - Open)#절대값을 구하세요
Gap

array([84.24023400000078, 54.109375, 56.36132799999905,
       10.691405999998096, 13.839843999998266, 25.128906999998435,
       100.52929699999731, 82.25, 200.35156199999983, 1.03125, 86.96875,
       14.660155999998096, 103.890625, 59.67968799999653,
       27.28906200000347, 1.0996090000007825, 64.21093699999983,
       15.900390999999217, 104.97070299999905, 4.25, 15.208984000000783,
       71.5, 29.759765999999217, 11.650389999998879, 64.609375,
       25.130859000000783, 20.628906999998435, 79.13085900000078,
       42.800781000001734, 27.728515999999217, 2.5, 11.880859000000783,
       18.519531000001734, 34.41992200000095, 18.220703000002686,
       9.800781000001734, 26.359375, 144.18945299999905, 25.0,
       48.07031300000017, 30.919922000000952, 7.060547000000952,
       234.00976500000252, 50.371093000001565, 32.390625,
       160.11132799999905, 38.17968700000347, 56.5, 5.410155999998096,
       24.099609000000783, 147.36914099999922, 32.66992200000095,
       12.0898430

In [439]:
np.max(Gap), arr[np.argmax(Gap),0]


(1041.8398430000016, '2018-02-08')